### ISSUE TITLE
Does not support iOS8

### ISSUE THREAD

**Issue by josephmisiti** [danielpovlsen/ios-icons-launch-images-generator#1]
I just tested this out - it does not seem to work for iOS 8. Is this correct? My steps for installation are as follows:
1. Run both bash scripts
2. Copy `Images.xcassets` into iOS project
3. Add folder to project via XCode
4. Clean + Recompile.

Let me know if I am missing something.

**Comment by danielpovlsen** [comment]
Hi Joseph!

I just created a new project with the latest Xcode 6.2. By default the Xcode project's "Launch Screen Files" (LaunchScreen.xib) is selected, which seems to disable the LaunchImage in the Asset Catalog. Deleting the LaunchScreen.xib ( + the reference to it) and selecting "Use Asset Catalog" seems to do the trick:

![screen shot 2015-03-27 at 12 02 15](https://cloud.githubusercontent.com/assets/77737/6866554/b550bc68-d479-11e4-8a17-1a208825c4f4.png)

Let me know if this solves your issue. :-)

Cheers,
Daniel

**Comment by josephmisiti** [comment]
That solved it! - not sure what I was doing wrong. Thanks!

**Comment by danielpovlsen** [comment]
Super! :-)
